meta:
  project_name: "devops-MinG-engine"
  project_version: v0.2

cache:
  grp:
    web_env:
  usr:
    ce_env:
  prj:
    m2: ${USER_HOME}/.m2
    gradle: ${USER_HOME}/.gradle
    npm: ${WORK_ROOT}/app/node_modules
  tmp:
    pass_package: # no default

build:
  dockerfile: MinG.Build.Dockerfile
  arg:
    - IMAGE_NAME=gradle
    - IMAGE_VERSION=5.0.0-jdk8
  # every_build, remove(default, --rm), preserve ... 등등 정해서
  # 이미지 이름 ${project_name}
  lifecycle: remove # remove(--rm) / preserve
  env:
    - JDK_VERSION=1.8
    - GRADLE_VERSION=5.0
  volume: # - {name}:{mount_path:if not defined use default}
    - m2
    - gradle
    - npm
  exec:
    - action: copy_in
      value: ["volume, credential, gradle.properteis, ${USER_HOME}/.gradle/gradle.properties"]
    - action: command
      value: ["gradle clean"]
    - action: command
      value: ["gradle yarn", "gradle build"]
    - action: copy_out
      value: ["volume, credential, ${USER_HOME}/.gradle/gradle.properties, gradle.properties"]
  extract:
    kos_pkg: /application/app/build/libs/app.jar

deploy:
  dockerfile: MinG.Deploy.Dockerfile
  arg:
    - JDK_VERSION=1.8
    - GRADLE_VERSION=5.0
    - APP_VERSION=20190111
  inject: # ADD
    kos_pkg: /application/app.jar
  entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  push_to:
    - target: dockerhub
      url: hub.docker.com
      name: scriptonbasestar/deploy_kos:20190111
#    - target: aws
#      url: awssssssssss
#      name: awssssss/deploy_backend:20190111
